### ISSUE TITLE
NEXUS failed in the NRT on 20221121 at 06z cycle

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#39] opened 2022-11-22 03:02 UTC
@bbakernoaa 
I am testing the latest workflow online-cmaq (hash=6990782) with ufs-weather-model (d31ee42) and NEXUS (d409056). However, the NEXUS failed three times around 43 to 44 minutes on 20221121 at 06z cycle and the NRT run stopped. 

Three NEXUS run log files can be found on Cactus at 
/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20221121
 nexus_emission_2022112106_s00.id_1669073434.log.0
nexus_emission_2022112106_s00.id_1669074115.log.0
nexus_emission_2022112106_s00.id_1669073434.log

The question is, how can we avoid such a failure during operational forecast?

Thanks,

Jianping

**Comment by bbakernoaa** [comment] 2022-11-22 14:22
@JianpingHuang-NOAA This looks like a problem with the input file 

```/lfs/h2/emc/lam/noscrub/RRFS_CMAQ/nexus_emissions/NEI2016v1/v2022-07/11/NEI2016v1_0.1x0.1_20161124_rwc.nc /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_00.19355361.cbqs01/tmp_NEXUS/00/input/NEI2016v1/v2022-07/11/NEI2016v1_0.1x0.1_20221124_rwc.nc```

Have you tried this day on HERA pointing to `/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus`?

**Comment by bbakernoaa** [comment] 2022-11-22 14:50
I looked a little more into the file it looks like there is something wrong with the longitudes in that file

```python 

a = xr.open_dataset('/lfs/h2/emc/lam/noscrub/RRFS_CMAQ/nexus_emissions/NEI2016v1/v2022-07/11/NEI2016v1_0.1x0.1_20161124_rwc.nc',decode_cf=False)
>>> print(a)
<xarray.Dataset>
Dimensions:       (lat: 288, lev: 1, lon: 640, time: 24)
Coordinates:
  * time          (time) float64 0.0 1.0 2.0 3.0 4.0 ... 20.0 21.0 22.0 23.0
  * lon           (lon) float64 nan nan nan nan nan nan ... nan nan nan nan nan
Dimensions without coordinates: lat, lev
Data variables: (12/60)
    FORM          (time, lev, lat, lon) float32 ...
    FORM_PRIMARY  (time, lev, lat, lon) float32 ...
    BENZ          (time, lev, lat, lon) float32 ...
    ALD2          (time, lev, lat, lon) float32 ...
    ALD2_PRIMARY  (time, lev, lat, lon) float32 ...
    NAPH          (time, lev, lat, lon) float32 ...
    ...            ...
    SO2           (time, lev, lat, lon) float32 ...
    SULF          (time, lev, lat, lon) float32 ...
    VOC_INV       (time, lev, lat, lon) float32 ...
    NOy           (time, lev, lat, lon) float32 ...
    NOx           (time, lev, lat, lon) float32 ...
    area          (lat, lon) float64 ...
Attributes:
    regrid_method:  conservative_normed
    Convention:     COARDS
    Format:         NetCDF-4
```

**Comment by bbakernoaa** [comment] 2022-11-22 14:53
It is messed up Hera too.  I'll go through and process them to fix coordinates right now

**Comment by bbakernoaa** [comment] 2022-11-22 15:28
@JianpingHuang-NOAA 

I was able to fix the file on HERA.  Can you copy it over to wcoss2 and try again

I also processed the rest of the files and have found a few more that have this same issue

```bash 
FIXING:  09/NEI2016v1_0.1x0.1_20160911_onroad.nc
FIXING:  11/NEI2016v1_0.1x0.1_20161124_rwc.nc
FIXING:  02/NEI2016v1_0.1x0.1_20160201_onroad.nc
```

**Comment by JianpingHuang-NOAA** [comment] 2022-11-22 15:31
Where is the location on Hera?

Thanks,

Jianping

**Comment by HaixiaLiu-NOAA** [comment] 2022-11-22 15:32
if these files are supposed to be fix files, should we move them to a central location?

**Comment by bbakernoaa** [comment] 2022-11-22 15:49
You can find it here: `/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/NEI2016v1/v2022-07`

@HaixiaLiu-NOAA I have brought this up several times.  ARL will maintain a research version in which we will continue to test and improve things (as is one of our tasks) but we should move these to a fixed file location much like we did for UFS-Aerosols where we moved all the emission files to the fixed location in the global workflow.  For instance on Hera @WalterKolczynski-NOAA keeps a copy of the emissions for UFS-Aerosols in `/scratch1/NCEPDEV/global/glopara/data/gocart_emissions` and I know @KateFriedman-NOAA also keeps a copy for use on WCOSS2.

This is important because we don't want these files to have any issues with being overwritten/deleted etc

**Comment by JianpingHuang-NOAA** [comment] 2022-11-22 16:49
The corrected files were copied to Cactus and Dogwood.

Regarding the file's locations, I agree with both suggestions, but we do
not have permissions to copy our input and fix files to the location like
/scratch1/NCEPDEV/global/glopara. We need to ask Kate for help every time
for any correction. Given the large uncertainties (e.g., change or errors)
during the development stage, we can keep what we have (Chan-Hoo creates a
symbolic link for emissions), Eventually we will or have to copy all input
(e..g, emissions, bc training data)  and fixed files to the NCO official
locations before the code is delivered to NCO. So I am not worrying about
that at this moment.  Thanks !

**Comment by bbakernoaa** [comment] 2022-11-22 18:57
@JianpingHuang-NOAA if this corrected this issue lets close it

**Comment by JianpingHuang-NOAA** [comment] 2022-11-22 19:00
I am testing it now. I will let you know once the test is passed.

Thanks,

Jianping

**Comment by JianpingHuang-NOAA** [comment] 2022-11-22 19:44
@Barry Baker - NOAA Federal ***@***.***>
The first part of NEXUS job was completed for 20221121 at 06z cycle. I
think the issue is fixed.

Thanks,

Jainping

**Comment by chan-hoo** [comment] 2022-11-23 13:33
@HaixiaLiu-NOAA, the NEXUS emission and point source data files should be located in the central locations of the HPC machines in order to merge the Online-CMAQ into the UFS SRW App in the future. As @bbakernoaa mentioned above, I remember @bbakernoaa and @ytangnoaa requested these to EMC management (maybe to @KateFriedman-NOAA). Please confirm this.

**Comment by HaixiaLiu-NOAA** [comment] 2022-11-23 14:02
@JianpingHuang-NOAA, can you let @chan-hoo know once your tests confirm all the fix files are ready to be copied over to the EMC fix file central locations? Thank you.

**Comment by bbakernoaa** [comment] 2022-11-23 14:44
@chan-hoo I completely agree.  This should be in a fixed file location.

**Comment by HaixiaLiu-NOAA** [comment] 2022-11-23 15:53
I'll give Kate a heads up to the need for the AQM fix files to be placed in the central EMC fix file location.

**Comment by KateFriedman-NOAA** [comment] 2022-11-28 14:05
Catching up after being on leave...let me know if/when there are updated gocart_emissions files to pull into the global fix file copies.

> AQM fix files to be placed in the central EMC fix file location.

These sound like new fix files. The current set I maintain are global-specific (GFS/GEFS) (fix and gocart_emissions). I would need to speak with EIB management about potentially adding new fix files to our global set, assuming that is what you're requesting here. Please confirm. FYI @aerorahul

**Comment by JianpingHuang-NOAA** [comment] 2022-11-30 01:48
@bbakernoaa NEXUS failed again on 20221129 at 06z cycle

Please check the following run log file on Cactus

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20221129/nexus_emission_2022112906_s00.id_1669761504.log

**Comment by bbakernoaa** [comment] 2022-11-30 14:55
It looks like the culprit is `/lfs/h2/emc/lam/noscrub/RRFS_CMAQ/nexus_emissions/NEI2016v1/v2022-07/12/NEI2016v1_0.1x0.1_20161209_nonpt.nc`

The coordinates are messed up here (ie they don't have any).  I'll go through and double check them all again.  

Fixed files 

``` 
FIXING:  06/NEI2016v1_0.1x0.1_20160613_onroad.nc
FIXING:  12/NEI2016v1_0.1x0.1_20161209_nonpt.nc
FIXING:  03/NEI2016v1_0.1x0.1_20160310_airports.nc
```

You should be able to copy these from HERA to wcoss.  Hera location: `/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/NEI2016v1/v2022-07`

@JianpingHuang-NOAA

**Comment by bbakernoaa** [comment] 2022-11-30 16:30
I did a much more robust check of the files looking for lat Lon time in the coordinates with the appropriate length and values and all the appropriate netcdf attributes.  This is why nexus failed was because of the coordinates and netcdf attributes in the input file.

**Comment by JianpingHuang-NOAA** [comment] 2022-11-30 17:57
Ok, can you get this fixed soon?

**Comment by bbakernoaa** [comment] 2022-11-30 18:01
All you should have to do is copy of those files and resubmit your job

**Comment by JianpingHuang-NOAA** [comment] 2022-11-30 18:11
Where do I get a copy of those files? from Hera?

**Comment by bbakernoaa** [comment] 2022-11-30 18:12
> It looks like the culprit is `/lfs/h2/emc/lam/noscrub/RRFS_CMAQ/nexus_emissions/NEI2016v1/v2022-07/12/NEI2016v1_0.1x0.1_20161209_nonpt.nc`
> 
> The coordinates are messed up here (ie they don't have any). I'll go through and double check them all again.
> 
> Fixed files
> 
> ```
> FIXING:  06/NEI2016v1_0.1x0.1_20160613_onroad.nc
> FIXING:  12/NEI2016v1_0.1x0.1_20161209_nonpt.nc
> FIXING:  03/NEI2016v1_0.1x0.1_20160310_airports.nc
> ```
> 
> You should be able to copy these from HERA to wcoss. Hera location: `/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/NEI2016v1/v2022-07`
> 
> @JianpingHuang-NOAA

**Comment by JianpingHuang-NOAA** [comment] 2022-11-30 19:39
The NEXUS run still failed at  reading the following file

/lfs/h2/emc/lam/noscrub/RRFS_CMAQ/nexus_emissions/NEI2016v1/v2022-07/12/
NEI2016v1_0.1x0.1_20161202_rwc.nc
/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_00.20110705.cbqs01/tmp_NEXUS/00/input/NEI2016v1/v2022-07/*12/NEI2016v1_0.1x0.1_20221202_rwc.nc
<http://NEI2016v1_0.1x0.1_20221202_rwc.nc>*

This is the same as before. I am not sure that you have fixed the above
file.

Please see the run log file on Cactus
/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20221129/nexus_emission_2022112906_s00.id_1669833511.log.0

Thanks.

**Comment by bbakernoaa** [comment] 2022-11-30 19:51
@JianpingHuang-NOAA this log doesn't actually show what is happening.... it is showing the linked file not the actual NEXUS simulation output.  Please look at the NEXUS.log and PET logs in the run directory as I've mentioned before.

**Comment by JianpingHuang-NOAA** [comment] 2022-11-30 22:07
@bbakernoaa 

 I checked the NEXUS.log and PET*log files and did not see much error message. Instead, I saw the following error message with the OUTPUT.186116 file at  /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_00.20113756.cbqs01/


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

HEMCO: Opening /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_00.20113756.cbqs01/tmp_NEXUS/00/input/NEI2016v1/v2022-07/1**2/NEI2016v1_0.1x0.1_20221202_nonpt.nc**

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

You fixed the file is for 1209, not for 1202.

FIXING:  12/NEI2016v1_0.1x0.1_2016**1209**_nonpt.nc

 Is this the reason that the nexus run still failed after I copied the fixed file for 1209?  Can you have a double check?

Thanks,

Jianping

**Comment by bbakernoaa** [comment] 2022-12-01 12:51
@JianpingHuang-NOAA  the files are linked files (do an ls -l and you will see what the actual name of the files are in the "fixed" directory).  This is what the nexus_nei_linker.py script does.  It pulls together all the emission files from each sector for a given day.  Not all emission sectors are available on every day and so the appropriate file is linked given a few factors including closest date and day of week. 

Anyway, something got messed up with the time dimension.  Could you please copy over the same files again?

**Comment by JianpingHuang-NOAA** [comment] 2022-12-01 15:16
@bbakernoaa It works now with the new fix.

Thanks,

**Comment by bbakernoaa** [comment] 2022-12-01 15:18
Awesome! Thanks @JianpingHuang-NOAA and sorry that the fix didn't work the first time.

**Comment by HaixiaLiu-NOAA** [comment] 2022-12-01 23:01
@bbakernoaa Thank you so much for helping get this NEXUS failure fixed. After going over the specifics of this issue, do you believe there is a way to avoid time dimension mess up in the future (for example, checking the file size and make sure the file size is greater than a threshold or something as a safeguard)? DO you think it is doable? Thanks.

**Comment by bbakernoaa** [comment] 2022-12-02 01:03
@HaixiaLiu-NOAA I tried to do a more thorough search and only the 3 files listed above turned up anything. So I think that we should be good to go. The problem is that there are hundreds of files and each sector is a different file size etc.  I think that with the check that we have done we should be good and when we do our retrospective we should catch anything else before it get to the final transition (which I don't foresee any other issues).

**Comment by JianpingHuang-NOAA** [comment] 2022-12-30 13:52
@bbakernoaa  NEXUS failed for today 06z cycle NRT run. The run log file can be found on Cactus at 

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20221230/nexus_emission_2022123006_s02.id_1672400732.log.0T

This is the 3rd splitted job which failed while other two splitted jobs (s00 and s01) were completed.

The run dir is located at 

 /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_02.27083396.cbqs01

Thanks,

Jianping

**Comment by JianpingHuang-NOAA** [comment] 2023-01-03 14:39
@bbakernoaa  Can you take a look at this issue?   Thanks !

**Comment by bbakernoaa** [comment] 2023-01-03 15:21
@JianpingHuang-NOAA I'm looking into it now

**Comment by JianpingHuang-NOAA** [comment] 2023-01-04 21:58
@bbakernoaa 

I checked out the latest workflow and still failed with next split job 2.  The run log file is available for your check.

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20221230/nexus_emission_2022123006_s02.id_1672867701.log.0  (Cactus)

Did you have a fix to this?

Thanks,

Jianping

**Comment by ytangnoaa** [comment] 2023-01-05 00:29
The useful information is in 
/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_02.27463345.cbqs01/OUTPUT.50494

HEMCO ERROR: Cannot find file for current simulation time: /lfs/h2/emc/ptmp/ji
 anping.huang/emc.para/tmp/nexus_emission_02.27463345.cbqs01/tmp_NEXUS/02/input/
 NEI2016v1/v2022-07/01/NEI2016v1_0.1x0.1_20220101_afdust_adj.nc - Cannot get fie
 ld NEI2016v1_AFDUSTADJ_PEC. Please check file name and time (incl. time range f
 lag) in the config. file


It looks that the year was not updated correctly (2022 not 2023)

**Comment by bbakernoaa** [comment] 2023-01-05 00:47
@JianpingHuang-NOAA this is the same issue as before. Please use the same fix I provided you. I’m working on the PR for this

**Comment by JianpingHuang-NOAA** [comment] 2023-01-05 02:35
@Barry Baker - NOAA Federal ***@***.***>  Do you mind resending
the fix?  Thanks !

**Closed as completed** 2023-01-27 14:47 UTC
